### ISSUE TITLE
Background Opacity transition required

### ISSUE THREAD

**Issue by eyadartist** [enesozturk/rn-swipeable-panel#75]
Hello,

Your repo is so amazing and I could made my Swipeable Panel and have a lot of customization.

However I found an issue, that when I close the panel the background Opacity is still appear until the panel close completely and the background disappear and that make the app annoying.

I just only need to customize the background opacity so that when I open and close the panel there will be a transition in the background

But anyway I love your repo ❤️❤️

**Comment by enesozturk** [comment]
Hi @eyadartist. Thanks for using **rn-swipeable-panel**. I am glad to hear these. 🥳 

Fading background opacity is my first todo feature. I will close this issue  for now because same [here](https://github.com/enesozturk/rn-swipeable-panel/issues/29). I have not been very available so far. But nowadays I can develop it. I will let you know. 👀
